---
apiVersion: v1
kind: Service
metadata:
  name: productnew
  labels:
    app: productnew
spec:
  type: NodePort
  selector:
    app: productnew
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: productnew
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productnew
    spec:
      containers:
      - name: productnew
        image: 107785248118.dkr.ecr.us-east-1.amazonaws.com/productnew:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
